App/Controllers/WorkingWithTechniqueController.cs
using System.Collections.Generic;
using App.BLL.Models;
using App.Common;
using Microsoft.AspNetCore.Mvc;
using App.Models;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using App.BLL.Interfaces;
using System.IO;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.Drawing;
using System.Diagnostics;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using System.Threading.Tasks;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;

namespace App.Controllers
{
    [Route("api/products")]
    public class WorkingWithTechniqueController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        ITechniqueService techniqueService;
        public WorkingWithTechniqueController(ITechniqueService techniqueService, IHostingEnvironment hostingEnvironment)
        {
            this.techniqueService = techniqueService;
            _hostingEnvironment = hostingEnvironment;
        }
        //[Authorize]
        //[HttpGet]
        //[ActionName("Delete")]
        //public IActionResult ConfirmDelete(int? id)
        //{
        //    if (id != null)
        //    {
        //        var technique = techniqueService.GetTechnique(id);
        //        if (technique != null)
        //        {
        //            var t = Mapper.Map<TechniqueDTO, Technique>(technique);
        //            return View(t);
        //        }
        //        return Content("The technique is not found!");
        //    }
        //    return Content("id is not set!");
        //}
        [Route("Export")]
        [HttpGet]
        public async Task<IActionResult> Export()
        {
            var tech = Mapper.Map<IEnumerable<TechniqueDTO>, List<Technique>>(techniqueService.GetTechniqueList());
            string sWebRootFolder = _hostingEnvironment.WebRootPath;
            string sFileName = @"technique.xlsx";
            var memory = new MemoryStream();
            using (var fs = new FileStream(Path.Combine(sWebRootFolder, sFileName), FileMode.Create, FileAccess.Write))
            {
                IWorkbook workbook;
                workbook = new XSSFWorkbook();
                ISheet excelSheet = workbook.CreateSheet("Technique");
                excelSheet.DefaultColumnWidth = 30;
                IRow row = excelSheet.CreateRow(0);
                row.CreateCell(0).SetCellValue("Наименование");
                row.CreateCell(1).SetCellValue("Модель");
                row.CreateCell(2).SetCellValue("Номер");
                row.CreateCell(3).SetCellValue("Количество");
                row.CreateCell(4).SetCellValue("Статус");
                row.CreateCell(5).SetCellValue("Примечание");

                for (int r = 1; r <= tech.Count; r++)
                {
                    row = excelSheet.CreateRow(r);
                    var item = tech[r - 1];
                    row.CreateCell(0).SetCellValue(item.Name);
                    row.CreateCell(1).SetCellValue(item.Model);
                    row.CreateCell(2).SetCellValue(item.Number);
                    row.GetCell(2).CellStyle.Alignment = HorizontalAlignment.Left;
                    row.CreateCell(3).SetCellValue(item.Amount);
                    if (item.Status == StatusModel.DontUsed) { row.CreateCell(4).SetCellValue("Не используется"); }
                    else { row.CreateCell(4).SetCellValue("Используется"); }
                    row.CreateCell(5).SetCellValue(item.Notation);
                }
                workbook.Write(fs);
            }
            using (var stream = new FileStream(Path.Combine(sWebRootFolder, sFileName), FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", sFileName);
        }
        [Authorize]
        [HttpDelete("{id}")]
        public IActionResult Delete(int? id)
        {

            var technique = techniqueService.GetTechnique(id);
            if (technique != null)
            {
                techniqueService.DeleteTechnique(technique);
                return Ok(technique);
            }
            return BadRequest();
        }

        [Authorize]
        [HttpGet("{id}")]
        public Technique Get(int? id)
        {
            if (id != null)
            {
                var technique = techniqueService.GetTechnique(id);
                if (technique != null)
                {
                    var t = Mapper.Map<TechniqueDTO, Technique>(technique);
                    return t;
                }
                return null;
            }
            return null;
        }
        //[Authorize]
        //public IActionResult SortForName()
        //{
        //    var tech = Mapper.Map<IEnumerable<TechniqueDTO>, List<Technique>>(techniqueService.GetTechniqueList());
        //    var orderTech = from t in tech
        //                    orderby t.Name
        //                    select t;

        //    return View("GetTechniqueList", orderTech);


        //}
        //[Authorize]
        //public IActionResult SortForModel()
        //{
        //    var tech = Mapper.Map<IEnumerable<TechniqueDTO>, List<Technique>>(techniqueService.GetTechniqueList());
        //    var orderTech = from t in tech
        //                    orderby t.Model
        //                    select t;
        //    return View("GetTechniqueList", orderTech);


        //}
        //[Authorize]
        //public IActionResult SortForNumber()
        //{
        //    var tech = Mapper.Map<IEnumerable<TechniqueDTO>, List<Technique>>(techniqueService.GetTechniqueList());
        //    var orderTech = from t in tech
        //                    orderby t.Number
        //                    select t;
        //    return View("GetTechniqueList", orderTech);


        //}
        //[Authorize]
        //public IActionResult SortForAmount()
        //{
        //    var tech = Mapper.Map<IEnumerable<TechniqueDTO>, List<Technique>>(techniqueService.GetTechniqueList());
        //    var orderTech = from t in tech
        //                    orderby t.Amount
        //                    select t;
        //    return View("GetTechniqueList", orderTech);


        //}
        //[Authorize]
        //public IActionResult SortForStatus()
        //{
        //    var tech = Mapper.Map<IEnumerable<TechniqueDTO>, List<Technique>>(techniqueService.GetTechniqueList());
        //    var orderTech = from t in tech
        //                    orderby t.Status
        //                    select t;
        //    return View("GetTechniqueList", orderTech);


        //}

        //[Authorize]
        //public IActionResult Update(int? id)
        //{
        //    if (id != null)
        //    {
        //        var technique = techniqueService.GetTechnique(id);
        //        if (technique != null)
        //        {
        //            var t = Mapper.Map<TechniqueDTO, Technique>(technique);
        //            return View(t);
        //        }
        //        return Content("The technique is not found!");
        //    }
        //    return Content("id is not set!");
        //}
        //[Authorize]
        //[HttpPost]
        //public IActionResult Update(Technique technique)
        //{
        //    if (ModelState.IsValid && technique != null)
        //    {
        //        var updatedTechnique = Mapper.Map<Technique, TechniqueDTO>(technique);
        //        techniqueService.SaveTechnique(updatedTechnique);
        //        return Ok(technique);
        //    }
        //    return BadRequest(ModelState);
        //}
        [Authorize]
        [HttpPost]
        public IActionResult Post([FromBody]Technique technique)//create
        {
            if (ModelState.IsValid && technique != null)
            {
                var createdTechnique = Mapper.Map<Technique, TechniqueDTO>(technique);
                techniqueService.SaveTechnique(createdTechnique);
                return Ok(technique);
            }
            return BadRequest(ModelState);
        }
        //[Authorize]
        //[HttpPost]
        //public IActionResult Found([FromBody]string txtValue)
        //{
        //    var tech = Mapper.Map<IEnumerable<TechniqueDTO>, List<Technique>>(techniqueService.GetTechniqueList());
        //    if (!string.IsNullOrEmpty(txtValue))
        //    {
        //        var foundTech = from t in tech
        //                        where t.Name.Contains(txtValue) || t.Model.Contains(txtValue) || t.Number.ToString().Contains(txtValue) || t.Amount.ToString().Contains(txtValue) || t.Status.ToString().Contains(txtValue) || t.Notation?.Contains(txtValue) != null
        //                        select t;
        //        return View("GetTechniqueList", foundTech);
        //    }
        //    return View("GetTechniqueList",tech);
        //}
        //[Authorize]
        //[HttpGet]
        //public IActionResult Create()
        //{
        //    return View();
        //}
        [Authorize]
        [HttpGet]
        public IEnumerable<Technique> Get()
        {
            var tech = Mapper.Map<IEnumerable<TechniqueDTO>, List<Technique>>(techniqueService.GetTechniqueList());
            return tech;
        }
        //protected override void Dispose(bool disposing)
        //{
        //    techniqueService.Dispose();
        //    base.Dispose(disposing);
        //}
    }
}

App/Views/WorkingWithTechnique/Create.cshtml
@model App.Models.Technique
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
</body>
</html>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css" />

<style>
    .form-width {
        max-width: 25rem;
    }

    .has-float-label {
        position: relative;
    }

        .has-float-label label {
            position: absolute;
            left: 0;
            top: 0;
            cursor: text;
            font-size: 75%;
            opacity: 1;
            -webkit-transition: all .2s;
            transition: all .2s;
            top: -.5em;
            left: 0.75rem;
            z-index: 3;
            line-height: 1;
            padding: 0 1px;
        }

            .has-float-label label::after {
                content: " ";
                display: block;
                position: absolute;
                background: white;
                height: 2px;
                top: 50%;
                left: -.2em;
                right: -.2em;
                z-index: -1;
            }

        .has-float-label .form-control::-webkit-input-placeholder {
            opacity: 1;
            -webkit-transition: all .2s;
            transition: all .2s;
        }

        .has-float-label .form-control:placeholder-shown:not(:focus)::-webkit-input-placeholder {
            opacity: 0;
        }

        .has-float-label .form-control:placeholder-shown:not(:focus) + label {
            font-size: 150%;
            opacity: .5;
            top: .3em;
        }

    .input-group .has-float-label {
        display: table-cell;
    }

        .input-group .has-float-label .form-control {
            border-radius: 0.25rem;
        }

        .input-group .has-float-label:not(:last-child) .form-control {
            border-bottom-right-radius: 0;
            border-top-right-radius: 0;
        }

        .input-group .has-float-label:not(:first-child) .form-control {
            border-bottom-left-radius: 0;
            border-top-left-radius: 0;
            margin-left: -1px;
        }
</style>
<div class="p-x-1 p-y-3  bg-secondary h-100">
    @using (Html.BeginForm("Create", "WorkingWithTechnique", FormMethod.Post, new { @class = "card card-block m-x-auto bg-faded form-width" }))
    {@Html.ValidationSummary(true)
    <legend class="m-b-1 text-xs-center">Добавление</legend>
    <div class="form-group input-group">
        <span class="has-float-label">
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control", @type = "text", @placeholder = "Наименование" })
            <span class="text-danger">    @Html.ValidationMessageFor(x => x.Name)</span>
            <label>Наименование</label>
        </span>

        <span class="has-float-label">
            @Html.TextBoxFor(x => x.Model, new { @class = "form-control", @type = "text", @placeholder = "Модель" })
            <span class="text-danger">   @Html.ValidationMessageFor(x => x.Model)</span>
            <label>Модель</label>
        </span>
    </div>
    <div class="form-group has-float-label">
        @Html.TextBoxFor(x => x.Number, new { @class = "form-control", @type = "text", @placeholder = "Номер" })
        <span class="text-danger">    @Html.ValidationMessageFor(x => x.Number)</span>
        <label>Номер</label>
    </div>
    <div class="form-group has-float-label">
        @Html.TextBoxFor(x => x.Amount, new { @class = "form-control", @type = "text", @placeholder = "Количество" })
        <span class="text-danger"> @Html.ValidationMessageFor(x => x.Amount)</span>
        <label>Количество</label>
    </div>
    <div class="form-group has-float-label">
        @Html.DropDownListFor(x => (x.Status), new SelectList(new[] { new { Status = 0, Name = "Используется" }, new { Status = 1, Name = "Не используется" }, }, "Status", "Name"), new { @class = "form-control custom-select" })

        <label>Статус</label>
    </div>
    <div class="form-group has-float-label">
        @Html.TextBoxFor(x => x.Notation, new { @class = "form-control", @type = "text", @placeholder = "Примечание" })
        <label>Примечание</label>
    </div>
    <div class="text-xs-center">
        <button class="btn btn-block btn-primary" type="submit">Добавить</button>
    </div>
    }
</div>

App/Views/WorkingWithTechnique/Delete.cshtml
@model App.Models.Technique
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
</body>
</html>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css" />

<style>
    .form-width {
        max-width: 25rem;
    }

    .has-float-label {
        position: relative;
    }

        .has-float-label label {
            position: absolute;
            left: 0;
            top: 0;
            cursor: text;
            font-size: 75%;
            opacity: 1;
            -webkit-transition: all .2s;
            transition: all .2s;
            top: -.5em;
            left: 0.75rem;
            z-index: 3;
            line-height: 1;
            padding: 0 1px;
        }

            .has-float-label label::after {
                content: " ";
                display: block;
                position: absolute;
                background: white;
                height: 2px;
                top: 50%;
                left: -.2em;
                right: -.2em;
                z-index: -1;
            }

        .has-float-label .form-control::-webkit-input-placeholder {
            opacity: 1;
            -webkit-transition: all .2s;
            transition: all .2s;
        }

        .has-float-label .form-control:placeholder-shown:not(:focus)::-webkit-input-placeholder {
            opacity: 0;
        }

        .has-float-label .form-control:placeholder-shown:not(:focus) + label {
            font-size: 150%;
            opacity: .5;
            top: .3em;
        }

    .input-group .has-float-label {
        display: table-cell;
    }

        .input-group .has-float-label .form-control {
            border-radius: 0.25rem;
        }

        .input-group .has-float-label:not(:last-child) .form-control {
            border-bottom-right-radius: 0;
            border-top-right-radius: 0;
        }

        .input-group .has-float-label:not(:first-child) .form-control {
            border-bottom-left-radius: 0;
            border-top-left-radius: 0;
            margin-left: -1px;
        }
</style>

<div class="p-x-1 p-y-3 bg-secondary h-100">
    @using (Html.BeginForm("Delete", "WorkingWithTechnique", FormMethod.Post, new { @class = "card card-block m-x-auto bg-faded form-width" }))
    {@Html.ValidationSummary(true)
    <legend class="m-b-1 text-xs-center">Удаление</legend>
    <div class="form-group input-group">
        <span class="has-float-label">
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control", @type = "text", @placeholder = "Наименование", @readonly = "true" })
            <span class="text-danger">    @Html.ValidationMessageFor(x => x.Name)</span>
            <label>Наименование</label>
        </span>

        <span class="has-float-label">
            @Html.TextBoxFor(x => x.Model, new { @class = "form-control", @type = "text", @placeholder = "Модель", @readonly = "true" })
            <span class="text-danger">   @Html.ValidationMessageFor(x => x.Model)</span>
            <label>Модель</label>
        </span>
    </div>
    <div class="form-group has-float-label">
        @Html.TextBoxFor(x => x.Number, new { @class = "form-control", @type = "text", @placeholder = "Номер", @readonly = "true" })
        <span class="text-danger">    @Html.ValidationMessageFor(x => x.Number)</span>
        <label>Номер</label>
    </div>
    <div class="form-group has-float-label">
        @Html.TextBoxFor(x => x.Amount, new { @class = "form-control", @type = "text", @placeholder = "Количество", @readonly = "true" })
        <span class="text-danger"> @Html.ValidationMessageFor(x => x.Amount)</span>
        <label>Количество</label>
    </div>
    <div class="form-group has-float-label">
        @Html.TextBoxFor(x => x.Status, new { @class = "form-control custom-select", @readonly = "true" })

        <label>Статус</label>
    </div>
    <div class="form-group has-float-label">
        @Html.TextBoxFor(x => x.Notation, new { @class = "form-control", @type = "text", @placeholder = "Примечание", @readonly = "true" })
        <label>Примечание</label>
    </div>
    <div class="text-xs-center">
        <button class="btn btn-block btn-primary" type="submit">Удалить</button>
    </div>
}
</div>

App/Views/WorkingWithTechnique/GetTechnique.cshtml
@model App.Models.Technique
<!DOCTYPE html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <style>
        td {
            width: 70px;
        }

        span {
            color: white;
        }
    </style>
    <title>Technique</title>
</head>
<body class="bg-secondary">
    <div class="row  justify-content-center align-items-center ">
        @using (Html.BeginForm("GetTechniqueList", "WorkingWithTechnique", FormMethod.Post, new { @class = "bg-dark justify-content-center align-items-center", role = "form" }))
        {<div class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <h2 class="text-white">Техника</h2>
                    <table class="table table-sm table table-striped table-dark">
                        <thead>
                            <tr>
                                <th>Наименование</th>
                                <th>Модель</th>
                                <th>Номер</th>
                                <th>Количество</th>
                                <th>Статус</th>
                                <th>Примечание</th>
                                <th>Действие</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td> @Model.Name</td>
                                <td> @Model.Model</td>
                                <td> @Model.Number</td>
                                <td>@Model.Amount</td>
                                <td>@Html.DisplayFor(x => Model.Status)</td>
                                <td>@Model.Notation</td>
                                <td>
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                            <span>Action</span>
                                        </button>
                                        <ul class="dropdown-menu bg-secondary">
                                            <li><a href="~/WorkingWithTechnique/Update/@Model.Id"><span>Редактировать</span></a></li>
                                            <li><a href="~/WorkingWithTechnique/Delete/@Model.Id"><span>Удалить</span></a></li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <a href="~/WorkingWithTechnique/Create" class="btn btn-info" role="button">Add new technique</a>
                </div>
            </div>}
    </div>
</body>

App/Views/WorkingWithTechnique/GetTechniqueList.cshtml
@model IEnumerable<App.Models.Technique>
<!DOCTYPE html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <style>
        td {
            width: 70px;
        }

        span {
            color: white;
        }

        th {
            color: lightblue;
        }

        a {
            color: lightblue;
        }

        .colortext {
            color: white;
        }

        ::-webkit-input-placeholder {
            color: white;
            opacity: 1;
        }
        /* webkit */
        :focus::-webkit-input-placeholder {
            color: transparent
        }
    </style>

    <title>Technique</title>
</head>
<body class="bg-secondary">
    <div class="row  justify-content-center align-items-center ">
        @using (Html.BeginForm("GetTechniqueList", "WorkingWithTechnique", FormMethod.Post, new { @class = "bg-dark justify-content-center align-items-center", role = "form" }))
        {<div class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <h2 class="text-white">Техника</h2>
                    @Html.TextBox("txtValue", null, new { @placeholder = "Поиск техники", @class = " bg-secondary border-dark border-top-0 colortext", @type = "search" })
                    <input type="button" value="Start" id="btnStart" />

                    <table class="table table-sm table table-striped table-dark">
                        <thead>
                            <tr>
                                <th> <a href="~/WorkingWithTechnique/SortForName">Наименование</a></th>
                                <th><a href="~/WorkingWithTechnique/SortForModel">Модель</a></th>
                                <th><a href="~/WorkingWithTechnique/SortForNumber">Номер</a></th>
                                <th><a href="~/WorkingWithTechnique/SortForAmount">Количество</a></th>
                                <th><a href="~/WorkingWithTechnique/SortForStatus">Статус</a></th>
                                <th>Примечание</th>
                                <th>Действие</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td> @item.Name</td>
                                    <td> @item.Model</td>
                                    <td> @item.Number</td>
                                    <td>@item.Amount</td>
                                    <td>@Html.DisplayFor(x => item.Status)</td>
                                    <td>@item.Notation</td>
                                    <td>
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                                <span>Action</span>
                                            </button>
                                            <ul class="dropdown-menu bg-secondary">
                                                <li><a href="~/WorkingWithTechnique/Update/@item.Id"><span>Редактировать</span></a></li>
                                                <li><a href="~/WorkingWithTechnique/Delete/@item.Id"><span>Удалить</span></a></li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <a href="~/WorkingWithTechnique/Create" class="btn btn-info" role="button">Add new technique</a>
                </div>
            </div>}
    </div>
</body>